import type { ButtonHTMLAttributes, HTMLAttributes, InputHTMLAttributes, ReactNode } from 'react';

export function Button({ variant = 'primary', className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: 'primary' | 'secondary' | 'danger' }) {
  const styles = { primary: 'bg-primary text-primary-foreground hover:opacity-90', secondary: 'border border-line bg-panel text-ink hover:border-primary/50', danger: 'bg-danger text-white hover:brightness-95' };
  return <button className={`inline-flex min-h-10 items-center justify-center rounded-xl px-4 text-sm font-semibold transition focus:outline-none focus:ring-2 focus:ring-highlight disabled:cursor-not-allowed disabled:opacity-50 ${styles[variant]} ${className}`} {...props} />;
}
export function Card({ children, className = '', ...props }: HTMLAttributes<HTMLDivElement>) { return <section className={`rounded-2xl border border-line bg-panel p-5 shadow-soft ${className}`} {...props}>{children}</section>; }
export function Badge({ children, tone = 'muted' }: { children: ReactNode; tone?: 'muted' | 'success' | 'warning' | 'danger' }) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${tone === 'success' ? 'bg-success/15 text-success' : tone === 'warning' ? 'bg-highlight/25 text-ink' : tone === 'danger' ? 'bg-danger/15 text-danger' : 'bg-muted text-muted-foreground'}`}>{children}</span>; }
export function Input(props: InputHTMLAttributes<HTMLInputElement>) { return <input className="min-h-11 w-full rounded-xl border border-line bg-canvas px-3.5 text-sm text-ink outline-none transition placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/15" {...props} />; }
export function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="grid gap-2 text-sm font-semibold text-ink">{label}{children}</label>; }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: ReactNode }) { return <div className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow && <p className="mb-2 text-xs font-bold uppercase tracking-[0.18em] text-vintage">{eyebrow}</p>}<h1 className="text-3xl font-bold tracking-tight text-ink sm:text-4xl">{title}</h1>{description && <p className="mt-2 max-w-2xl text-muted-foreground">{description}</p>}</div>{action}</div>; }
export function StateMessage({ type, message, onRetry }: { type: 'loading' | 'empty' | 'error'; message: string; onRetry?: () => void }) { return <div className="rounded-2xl border border-dashed border-line bg-panel/60 p-8 text-center text-sm text-muted-foreground">{type === 'loading' && <span className="mr-2 inline-block h-4 w-4 animate-spin rounded-full border-2 border-primary border-t-transparent align-[-2px]" />}{message}{type === 'error' && onRetry && <div className="mt-4"><Button variant="secondary" onClick={onRetry}>Try again</Button></div>}</div>; }
