/**
 * Step 10, part 5: create the three juror subnames inside our own subregistry.
 *
 * Calls `IStandardRegistry.register()` directly on our UserRegistry proxy (not through any registrar or
 * pricing oracle — those exist for `.eth` itself, not for names inside a registry we own). The operator
 * holds ROLE_REGISTRAR at ROOT_RESOURCE there from part 2's `initialize()`, which is exactly what
 * `_register()`'s `_checkRoles(ROOT_RESOURCE, ROLE_REGISTRAR, msg.sender)` requires (read directly from
 * PermissionedRegistry.sol).
 *
 * Each subname is owned by the operator, not the juror: registry-level authority (who can change a
 * subname's own subregistry/resolver, or transfer it) stays with the one trusted operator key, consistent
 * with the trust model the rest of the project already documents. The juror's own key gets no registry
 * role at all here — its write access is scoped entirely inside the resolver (part 6), to exactly the
 * `profile`/`strategy` text-record parts, never to the subname's registry entry. This is a design decision,
 * not something the spec dictated.
 *
 * Expiry is capped at nyaya.eth's own expiry (read from part 1's record), so a subname can never outlive
 * its parent — there's no cross-registry enforcement of that in the contracts, so it's enforced here.
 *
 * Each juror's address is a FRESH throwaway keypair generated by this script, not a key reused from the
 * Hedera side. `.claude/rules/contracts.md` is explicit that generated testnet keys are printed for
 * inspection and never written to a file in the repo or to `.env`, and never reused — this follows that
 * rule rather than the (wrong) earlier assumption that a Hedera JUROR_PK could just be reused here, which
 * doesn't hold anyway: `.env` has no JUROR_PK/JUROR_B_PK/JUROR_C_PK, confirmed before writing this.
 * Only each juror's ADDRESS is persisted to deployments/sepolia.json (public, and needed by parts 6-7 to
 * grant/check roles); the private key is printed to stdout once and is the caller's to keep or discard —
 * part 7, which is the only later step that needs to sign as the juror, takes it back in via
 * JUROR_PK / JUROR_B_PK / JUROR_C_PK supplied fresh at invocation time, not stored.
 */
import { Interface, keccak256, toUtf8Bytes, ZeroAddress, Wallet } from "ethers";
import {
  JUROR_LABELS,
  NYAYA_NAME,
  abi,
  assertFunctionsExist,
  connect,
  contract,
  findLog,
  readDeployments,
  revertName,
  send,
  writeDeployments,
} from "./ensConfig.js";
import { ETH_REGISTRAR_GRANTS_OWNER } from "./roles.js";

const GAS = { register: 300_000n } as const;

async function main() {
  const { provider, operator } = connect();
  const registryAbi = abi("UserRegistryImpl");
  assertFunctionsExist(registryAbi, ["register", "getState"], "UserRegistryImpl");
  const iface = new Interface(registryAbi as never);

  const d = readDeployments();
  const subregistry = d.ens?.subregistry;
  const resolver = d.ens?.resolver;
  const nyayaExpiry = d.ens?.nyayaExpiry;
  if (!subregistry) throw new Error("No subregistry recorded. Run 2_deploySubregistry.ts first.");
  if (!resolver) throw new Error("No resolver recorded. Run 3_deployResolver.ts first.");
  if (!nyayaExpiry) throw new Error("No nyayaExpiry recorded. Run 1_registerNyaya.ts first.");

  const registry = contract(subregistry, registryAbi, provider);

  for (const label of JUROR_LABELS) {
    const existing = d.ens?.jurors?.[label];
    let jurorAddress = existing?.address;
    if (!jurorAddress) {
      const jurorWallet = Wallet.createRandom();
      jurorAddress = jurorWallet.address;
      console.log(`${label}: generated a fresh throwaway key.`);
      console.log(`  address:     ${jurorWallet.address}`);
      console.log(`  private key: ${jurorWallet.privateKey}  (printed once, not stored anywhere; keep it if you need it for part 7)`);
      writeDeployments({ ens: { jurors: { [label]: { address: jurorAddress } } } });
    }
    const fullName = `${label}.${NYAYA_NAME}`;
    // Within our UserRegistry, storage is keyed by the plain labelhash of "juror-a" alone (LibLabel.id,
    // read directly: `uint256(keccak256(bytes(label)))`) — NOT the full DNS namehash of "juror-a.nyaya.eth".
    // That full namehash is a resolver-only concept, used in part 6, never here.
    const labelId = BigInt(keccak256(toUtf8Bytes(label)));

    if (existing?.tokenId) {
      console.log(`${fullName}: already registered (tokenId ${existing.tokenId}). Skipping.`);
      continue;
    }

    // A prior run's register() may have succeeded without the record being written (crash between the tx
    // and the write). Check the registry itself before re-registering.
    const state = (await registry.getState(labelId)) as { status: bigint; tokenId: bigint };
    if (Number(state.status) === 2 /* REGISTERED */) {
      writeDeployments({ ens: { jurors: { [label]: { address: jurorAddress, tokenId: state.tokenId.toString() } } } });
      console.log(`${fullName}: found already REGISTERED on-chain (tokenId ${state.tokenId}). Recorded, skipping register().`);
      continue;
    }

    let receipt;
    try {
      receipt = await send(
        provider,
        operator,
        `register(${fullName})`,
        {
          to: subregistry,
          data: iface.encodeFunctionData("register", [
            label,
            operator.address,
            ZeroAddress, // no further children under a leaf juror subname
            resolver,
            ETH_REGISTRAR_GRANTS_OWNER,
            BigInt(nyayaExpiry),
          ]),
        },
        GAS.register,
      );
    } catch (error) {
      throw new Error(`register(${fullName}) reverted: ${revertName(error, iface)}`);
    }

    const registered = findLog<{ name: "LabelRegistered"; args: { tokenId: bigint } }>(
      receipt,
      iface,
      subregistry,
      "LabelRegistered",
    );
    const tokenId = registered.args.tokenId;

    writeDeployments({
      ens: { jurors: { [label]: { address: jurorAddress, tokenId: tokenId.toString(), registerTx: receipt.hash } } },
    });
    console.log(`${fullName}: registered, tokenId ${tokenId}, juror key ${jurorAddress}, tx ${receipt.hash}`);
  }

  console.log("\nAll three juror subnames processed.");
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
